// 'HNL11385532': {
//     trackingNumber: 'HNL11385532',
//     status: 'in-transit',
//     estimatedDelivery: 'Feb 9, 2026',
//     lastUpdated: '3 hours ago',
//     origin: 'Robinson Road, Singapore',
//     destination: ' New Jersey, USA',
//     progress: 90,
//     events: [
//       // { date: 'Nov 12', time: '13:11', location: "Li'Undray Rocks", status: 'In Transit', isCompleted: true, isCurrent: true },
//       { date: 'Feb 9', time: '09:31', location: 'New Jersey', status: 'On Hold; Customs Clearance', isCompleted: false },
//       { date: 'Feb 6', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 3', time: '04:18', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Jan 28', time: '17:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Jan 23', time: '07:22', location: 'Robinson Road, Singapore', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//   'HNL3450166': {
//     trackingNumber: 'HNL3450166',
//     status: 'in-transit',
//     estimatedDelivery: 'February 13, 2026',
//     lastUpdated: '2 hours ago',
//     origin: 'Paris, France',
//     destination: 'Surrey, England',
//     progress: 89,
//     events: [
//       { date: 'Feb 10', time: '09:31', location: 'Calais border', status: 'On Hold; Customs Clearance', isCompleted: false },
//       { date: 'Feb 9', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 6', time: '10:13', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true, isCurrent: true },
//       { date: 'Feb 2', time: '14:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true, isCurrent: true },
//       { date: 'Jan 31', time: '11:45', location: 'A350-900ULR, Cargo', status: 'Departed Facility', isCompleted: true },
//       { date: 'Jan 28', time: '06:20', location: 'Rue Royale, Paris', status: 'Arrived at Facility', isCompleted: true },
//       { date: 'Jan 26', time: '15:15', location: 'Rue Royale, Paris', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//   'HNL987654321': {
//     trackingNumber: 'HNL987654321',
//     status: 'in-transit',
//     estimatedDelivery: 'February 13, 2026',
//     lastUpdated: '2 hours ago',
//     origin: 'Paris, France',
//     destination: 'Pretoria, South Africa',
//     progress: 11,
//     events: [
//       // { date: 'Jan 20', time: '10:45', location: 'Chicago, IL', status: 'Delivered', isCompleted: true, isCurrent: true },
//       // { date: 'Jan 20', time: '07:30', location: 'Chicago, IL', status: 'Out for Delivery', isCompleted: true },
//       // { date: 'Jan 19', time: '23:00', location: 'Chicago, IL', status: 'Arrived at Facility', isCompleted: true },
//       { date: 'Jan 26', time: '15:15', location: 'Rue Royale, Paris', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//   'HNL10385532': {
//     trackingNumber: 'HNL10385532',
//     status: 'in-transit',
//     estimatedDelivery: 'Feb 13, 2026',
//     lastUpdated: '1 hours ago',
//     origin: 'Robinson Road, Singapore',
//     destination: ' California, USA',
//     progress: 91,
//     events: [
//       { date: 'Feb 12', time: '13:06', location: "Los Angeles International Airport (LAX)", status: 'On Hold; Customs Clearance', isCompleted: false, isCurrent: true },
//       { date: 'Feb 11', time: '22:31', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 10', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 9', time: '14:18', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 9', time: '07:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 7', time: '07:22', location: 'Robinson Road, Singapore', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//     'HNL21385532': {
//     trackingNumber: 'HNL21385532',
//     status: 'in-transit',
//     estimatedDelivery: 'Feb 25, 2026',
//     lastUpdated: '7 hours ago',
//     origin: 'RR, United States',
//     destination: 'Khemisset, Morocco',
//     progress: 95,
//     events: [
//       { date: 'Feb 27', time: '13:06', location: "Tanger Med Port, Morocco", status: 'On Hold; Customs Clearance', isCompleted: false, isCurrent: true },
//       { date: 'Feb 25', time: '22:31', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 22', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 19', time: '14:18', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 14', time: '07:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 12', time: '07:22', location: 'RR, United States', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//   'HNL21385533': {
//     trackingNumber: 'HNL21385533',
//     status: 'in-transit',
//     estimatedDelivery: 'Mar 06, 2026',
//     lastUpdated: '2 hours ago',
//     origin: 'New York, United States',
//     destination: 'Januaria, Brazil',
//     progress: 90,
//     events: [
//       { date: 'Mar 2', time: '18:06', location: "Brasilia-Presidente Juscelino Kubitscheck International Airport (BSB)", status: 'On Hold; Customs Clearance', isCompleted: false, isCurrent: true },
//       // { date: 'Feb 25', time: '22:31', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Mar 2', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 28', time: '14:18', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 27', time: '11:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 25', time: '07:22', location: '10 Hudson Yards, New York, NY 10001, United States', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//     'HNL21385534': {
//     trackingNumber: 'HNL21385534',
//     status: 'in-transit',
//     estimatedDelivery: 'Mar 06, 2026',
//     lastUpdated: '1 hours ago',
//     origin: 'New York, United States',
//     destination: 'Andhra Pradesh, India',
//     progress: 90,
//     events: [
//       { date: 'Mar 2', time: '18:06', location: "Rajiv Ghandi International Airport (HYD), Hyderabad", status: 'On Hold; Customs Clearance', isCompleted: false, isCurrent: true },
//       // { date: 'Feb 25', time: '22:31', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Mar 2', time: '14:53', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 28', time: '14:18', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 27', time: '11:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Feb 25', time: '07:22', location: '10 Hudson Yards, New York, NY 10001, United States', status: 'Picked Up', isCompleted: true },
//     ],
//   },
//   'HNL21385535': {
//     trackingNumber: 'HNL21385535',
//     status: 'in-transit',
//     estimatedDelivery: 'Apr 16, 2026',
//     lastUpdated: '23 minutes ago',
//     origin: 'New York, United States',
//     destination: 'Tipaza Province, Algeria',
//     progress: 90,
//     events: [
//       { date: 'Apr 14', time: '18:06', location: "Houari Boumediene Airport (ALG), Algiers", status: 'On Hold; Customs Clearance', isCompleted: false, isCurrent: true },
//       { date: 'Apr 13', time: '11:02', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Apr 12', time: '11:38', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Apr 11', time: '21:30', location: 'A350-900ULR, Cargo', status: 'In Transit', isCompleted: true },
//       { date: 'Apr 9', time: '07:22', location: '10 Hudson Yards, New York, NY 10001, United States', status: 'Picked Up', isCompleted: true },
//     ],
//   },